# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_analysis', '0002_auto_20170114_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinsight',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.CustomerWebsite'),
        ),
    ]
