# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analysis', '0004_remove_pageinsight_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinsight',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ensenar en el front office'),
        ),
    ]
