# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_analysis', '0005_pageinsight_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleresult',
            name='pageInsight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='app_analysis.PageInsight'),
        ),
    ]
