# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0030_auto_20170114_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished Date')),
                ('task', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.Customer', verbose_name='Customer')),
                ('customerWebsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.CustomerWebsite', verbose_name='CustomerWebsite')),
            ],
        ),
    ]
