# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0030_auto_20170114_1610'),
        ('app_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.Customer', verbose_name='Customer')),
                ('customerWebsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.CustomerWebsite', verbose_name='CustomerWebsite')),
            ],
        ),
        migrations.RemoveField(
            model_name='customertask',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customertask',
            name='customerWebsite',
        ),
        migrations.RemoveField(
            model_name='customertask',
            name='finished',
        ),
        migrations.AddField(
            model_name='customertask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='customertask',
            name='task',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Name'),
        ),
    ]
