# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0030_auto_20170114_1610'),
        ('app_manager', '0002_auto_20170127_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.Customer'),
        ),
    ]
