# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0005_auto_20170127_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertask',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'OnGoing'), (2, 'Completed')], null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customertask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.CustomerProject'),
        ),
        migrations.AlterField(
            model_name='customertask',
            name='task',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Task'),
        ),
    ]
