# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Project Name')),
                ('customer_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Customer Name')),
                ('customer_website', models.CharField(blank=True, max_length=400, null=True, verbose_name='Customer Website')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
            ],
        ),
    ]
