# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicar'),
        ),
    ]
