# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0004_auto_20170218_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicar'),
        ),
    ]
