# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Apellido')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('adress', models.CharField(blank=True, max_length=400, null=True, verbose_name='Adress')),
                ('nif', models.CharField(blank=True, max_length=400, null=True, verbose_name='ID Number(NIF/NIE)')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
