# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_smallfix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallfix',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Customer'),
        ),
        migrations.AlterField(
            model_name='smallfix',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='smallfix',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='smallfix',
            name='url',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Url'),
        ),
    ]
