# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20170102_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallfix',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url'),
        ),
    ]
