# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_auto_20170102_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixesBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('APROVED', 'APROVED'), ('DONE', 'DONE'), ('CANCELED', 'CANCELED')], default='REQUESTED', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='smallfix',
            name='title',
        ),
        migrations.RemoveField(
            model_name='smallfix',
            name='url',
        ),
        migrations.AddField(
            model_name='smallfix',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
