# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_auto_20170103_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallfix',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.FixesBatch'),
        ),
    ]
