# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_smallfix_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallfix',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.FixesBatch'),
        ),
    ]
