# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_auto_20170103_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='smallfix',
            name='file',
            field=models.ManyToManyField(to='app_users.FixAttachment'),
        ),
    ]
