# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_auto_20170104_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FixesBatch',
            new_name='FixesCapsule',
        ),
        migrations.RenameField(
            model_name='smallfix',
            old_name='batch',
            new_name='capsule',
        ),
    ]
