# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallfix',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ASSIGNED', 'ASSIGNED'), ('APROVED', 'APROVED'), ('DONE', 'DONE'), ('CANCELED', 'CANCELED')], default='REQUESTED', max_length=20),
        ),
    ]
