# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_auto_20170106_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixescapsule',
            options={'verbose_name': 'Capsula', 'verbose_name_plural': 'Capsulas'},
        ),
        migrations.AddField(
            model_name='smallfix',
            name='feedback',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Valoracion Technica'),
        ),
    ]
