# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0018_stripetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripetransaction',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
