# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_auto_20170107_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixescapsule',
            name='dev_entry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dev Start'),
        ),
        migrations.AddField(
            model_name='fixescapsule',
            name='dev_exit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dev Exit'),
        ),
    ]
