# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0020_auto_20170108_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallfix',
            name='to_dev',
            field=models.BooleanField(default=False),
        ),
    ]
