# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0021_smallfix_to_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallfix',
            name='to_dev',
            field=models.BooleanField(default=True),
        ),
    ]
