# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0022_auto_20170110_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('credits', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('credits', models.IntegerField(blank=True, default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.CustomerWallet'),
        ),
    ]
