# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0023_auto_20170110_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_users.CustomerTransaction'),
            preserve_default=False,
        ),
    ]
