# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0026_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
