# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0027_remove_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='web',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='WEB'),
        ),
    ]
