# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0029_auto_20170114_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwebsite',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_users.Customer'),
        ),
    ]
